apiVersion: v1
kind: Service
metadata: # kpt-merge: /gnb-service
  name: gnb-service
  labels:
    app.kubernetes.io/version: "v3.2.6"
    app: ueransim
    component: gnb
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|gnb-service'
spec:
  type: ClusterIP
  ports:
  - name: gnb-ue
    port: 4997
    protocol: UDP
  selector:
    app: ueransim
    component: gnb
