apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: /n3
  name: n3
  annotations:
    nephio.org/network-name: n3
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: apps/v1.Deployment.ueransimgnb-example
    specializer.nephio.org/namespace: ueransim
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Interface|default|n3'
spec:
  networkInstance:
    name: vpc-ran
  cniType: macvlan
  attachmentType: vlan
